/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de.zmiter.liefermonitor01.Logik;

import de.zmiter.liefermonitor01.DBObjekte.Artikel;
import de.zmiter.liefermonitor01.DBObjekte.Lieferung;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author lepeschko
 */
public class NeuAnforderung01 extends javax.swing.JFrame {

    /**
     * Creates new form NeuAnforderung
     */
    DBManager dbManager = new DBManager();
    private ArrayList<Artikel> artList = new ArrayList<>();

    
    public NeuAnforderung01() {
     
        startComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void startComponents(){
         jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jComboBoxDay = new javax.swing.JComboBox<>();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        jButton3.setText("jButton3");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Neue Anforderung");
        setLocation(new java.awt.Point(150, 150));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea1.setColumns(100);
        jTextArea1.setRows(1);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bezeichnung der Ware(DE)"));
        jTextArea1.setLineWrap(false);
        jTextArea1.setWrapStyleWord(false);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea11.setColumns(100);
        jTextArea11.setRows(1);
        jTextArea11.setBorder(javax.swing.BorderFactory.createTitledBorder("Goods Description (EN)"));
        jTextArea11.setLineWrap(false);
        jTextArea11.setWrapStyleWord(false);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane11.setViewportView(jTextArea11);

        jTextArea2.setColumns(6);
        jTextArea2.setRows(1);
        jTextArea2.setTabSize(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder("Menge"));
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(5);
        jTextArea3.setRows(1);
        jTextArea3.setTabSize(5);
        jTextArea3.setBorder(javax.swing.BorderFactory.createTitledBorder("Einheit"));
        jScrollPane3.setViewportView(jTextArea3);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 51));
        jButton1.setText("Eintragen");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, 10)
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(100);
        jTextArea4.setBorder(javax.swing.BorderFactory.createTitledBorder("Bestellliste"));
        jScrollPane4.setViewportView(jTextArea4);

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea5.setColumns(10);
        jTextArea5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextArea5.setRows(1);
        jTextArea5.setBorder(javax.swing.BorderFactory.createTitledBorder("Wunschliefertermin"));
        jScrollPane5.setViewportView(jTextArea5);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder("Baustelle/ Abteilung"));

        jScrollPane6.setBorder(javax.swing.BorderFactory.createTitledBorder("Kommentar/ Zusatzinfo"));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Anforderung speichern");
        
        // Инициализация ComboBox для выбора даты
        initializeDateComboBoxes();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Suchen"));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setText("OK");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jComboBox3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setText("jMenuItem3");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        
        // Добавляем обработчики событий
        setupEventHandlers();
    }
    
    /**
     * Настройка обработчиков событий
     */
    private void setupEventHandlers() {
        // Обработчик для кнопки jButton1
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        // Обработчик для Enter и Tab в jTextArea1
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    addArtikelFromTextArea();
                    evt.consume(); // Предотвращаем добавление новой строки в текстовое поле
                } else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_TAB) {
                    jTextArea11.requestFocusInWindow();
                    evt.consume(); // Предотвращаем стандартное поведение Tab
                }
            }
        });
         jTextArea11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    addArtikelFromTextArea();
                    evt.consume(); // Предотвращаем добавление новой строки в текстовое поле
                } else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_TAB) {
                    jTextArea2.requestFocusInWindow();
                    evt.consume(); // Предотвращаем стандартное поведение Tab
                }
            }
        });
        
        jTextArea2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    addArtikelFromTextArea();
                    evt.consume(); // Предотвращаем добавление новой строки в текстовое поле
                } else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_TAB) {
                    jTextArea3.requestFocusInWindow();
                    evt.consume(); // Предотвращаем стандартное поведение Tab
                }
            }
        });
        jTextArea3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    addArtikelFromTextArea();
                    evt.consume(); // Предотвращаем добавление новой строки в текстовое поле
                }
            }
        });
        // Обработчик для Enter в jTextField1 (поиск)
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    performSearch();
                }
            }
        });
        
        // Обработчик для кнопки jButton2 (сохранение заявки)
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
    }
    
    /**
     * Обработчик нажатия кнопки jButton1
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        addArtikelFromTextArea();
    }
    
    /**
     * Обработчик нажатия кнопки jButton2 (Anforderung speichern)
     * Создает новый экземпляр Lieferung с данными из формы
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        createLieferungFromForm();
    }
    
    /**
     * Метод для создания нового экземпляра Lieferung из данных формы
     */
    private void createLieferungFromForm() {
        try {
            // Создаем новый экземпляр Lieferung
            Lieferung lieferung = new Lieferung();
            
            // Заполняем поле beschreibung из jTextArea4
            String beschreibung = jTextArea4.getText().trim();
            lieferung.setBeschreibung(beschreibung);
            
            // Заполняем поле menge из jTextArea2 (преобразуем в float)
            float menge = 0.0f;
            String mengeText = jTextArea2.getText().trim();
            if (!mengeText.isEmpty()) {
                try {
                    menge = Float.parseFloat(mengeText);
                } catch (NumberFormatException e) {
                    System.err.println("Fehler beim Parsen der Menge: " + e.getMessage());
                    menge = 0.0f;
                }
            }
            lieferung.setMenge(menge);
            
            // Устанавливаем поля neu и aktiv в true
            lieferung.setNeu(true);
            lieferung.setAktiv(true);
            
            // Заполняем поле einhMenge из jTextArea3
            String einhMenge = jTextArea3.getText().trim();
            lieferung.setEinhMenge(einhMenge);
            
            // Заполняем поле wunschLieferdatum из jTextArea5
            String wunschLieferdatum = jTextArea5.getText().trim();
            lieferung.setWunschLieferDatum(wunschLieferdatum);
            
            // Заполняем поле projectName из jComboBox1 (активное значение)
            String projectName = "";
            if (jComboBox1.getSelectedItem() != null) {
                projectName = jComboBox1.getSelectedItem().toString();
            }
            lieferung.setProjectName(projectName);
            
            // Заполняем поле kommentarBS из jTextArea6
            String kommentarBS = jTextArea6.getText().trim();
            lieferung.setKommentarBS(kommentarBS);
            
            // Сохраняем Lieferung в базу данных
            boolean saved = dbManager.addInTabLif(lieferung);
            
            if (saved) {
                System.out.println("Lieferung erfolgreich in die Datenbank gespeichert: " + lieferung.getBeschreibung());
                // Можно добавить диалоговое окно с сообщением об успехе
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Anforderung wurde erfolgreich gespeichert!", 
                    "Erfolg", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                // Очищаем форму после успешного сохранения
                clearForm();
            } else {
                System.err.println("Fehler beim Speichern der Lieferung in die Datenbank");
                // Показываем сообщение об ошибке
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Fehler beim Speichern der Anforderung!\nBitte versuchen Sie es erneut.", 
                    "Fehler", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                 clearForm();
            }
            
        } catch (Exception e) {
            System.err.println("Fehler beim Erstellen der Lieferung: " + e.getMessage());
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Fehler beim Erstellen der Anforderung:\n" + e.getMessage(), 
                "Fehler", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Метод для очистки формы после успешного сохранения
     */
    private void clearForm() {
        jTextArea1.setText("");
        jTextArea2.setText("");
        jTextArea3.setText("");
        jTextArea4.setText("");
        jTextArea5.setText("");
        jTextArea6.setText("");
        jTextArea11.setText("");
        jTextField1.setText("");
        artList.clear();
        // Сбрасываем комбобоксы на первый элемент, если есть
        if (jComboBox1.getItemCount() > 0) {
            jComboBox1.setSelectedIndex(0);
        }
    }
    
    /**
     * Метод для добавления статьи из jTextArea1 в список и jTextArea4
     */
    private void addArtikelFromTextArea() {
        String text = jTextArea1.getText().trim() + "(" + jTextArea11.getText().trim() + ") " + "  " + jTextArea2.getText().trim() + "  " + jTextArea3.getText().trim(); 

        if (text.isEmpty()) {
            return; // Не добавляем пустой текст
        }
        
        // Создаем новый экземпляр Artikel
        Artikel artikel = new Artikel();
        artikel.setMaterial_DE(text);
        artikel.setWeight(jTextArea2.getText().trim());
       
        
        // Добавляем в список
        artList.add(artikel);
        
        // Добавляем текст в jTextArea4 с новой строки
        String currentText = jTextArea4.getText();
        if (currentText.isEmpty()) {
            jTextArea4.setText(text);
        } else {
            jTextArea4.setText(currentText + "\n" + text);
        }
        
        // Очищаем jTextArea1
        jTextArea1.setText("");
          jTextArea2.setText("");
            jTextArea3.setText("");
              jTextArea11.setText("");
    }
    
    /**
     * Метод для выполнения поиска в базе данных и заполнения jComboBox2
     */
    private void performSearch() {
        String searchText = jTextField1.getText().trim();
        if (searchText.isEmpty()) {
            // Если поле пустое, очищаем комбобокс
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>());
            return;
        }
        
        // Выполняем поиск в базе данных
        ArrayList<Artikel> searchResults = dbManager.searchArtikel(searchText);
        
        // Создаем массив строк для комбобокса
        String[] comboItems = new String[searchResults.size()];
        for (int i = 0; i < searchResults.size(); i++) {
            Artikel artikel = searchResults.get(i);
            // Формируем строку для отображения (используем material_DE, если оно не пустое, иначе material_EN)
            String displayText = artikel.getMaterial_DE();
            if (displayText == null || displayText.trim().isEmpty()) {
                displayText = artikel.getMaterial_EN();
            }
            if (displayText == null || displayText.trim().isEmpty()) {
                displayText = "Artikel ID: " + artikel.getId();
            }
            comboItems[i] = displayText;
        }
        
        // Устанавливаем модель комбобокса с результатами поиска
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(comboItems));
    }
    
    /**
     * Инициализация ComboBox для выбора даты
     */
    private void initializeDateComboBoxes() {
        Calendar cal = Calendar.getInstance();
        
        // Инициализация ComboBox для месяца (сначала, так как нужен для updateDaysInMonth)
        String[] months = {"Januar", "Februar", "März", "April", "Mai", "Juni", 
                          "Juli", "August", "September", "Oktober", "November", "Dezember"};
        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(months));
        jComboBoxMonth.setBorder(javax.swing.BorderFactory.createTitledBorder("Monat"));
        // Устанавливаем текущий месяц по умолчанию
        jComboBoxMonth.setSelectedIndex(cal.get(Calendar.MONTH));
        
        // Инициализация ComboBox для года (нужен для updateDaysInMonth)
        String[] years = new String[81]; // 2010-2090 = 81 год
        for (int i = 0; i < 81; i++) {
            years[i] = String.valueOf(2010 + i);
        }
        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(years));
        jComboBoxYear.setBorder(javax.swing.BorderFactory.createTitledBorder("Jahr"));
        // Устанавливаем текущий год по умолчанию
        int currentYear = cal.get(Calendar.YEAR);
        if (currentYear >= 2010 && currentYear <= 2090) {
            jComboBoxYear.setSelectedItem(String.valueOf(currentYear));
        } else {
            jComboBoxYear.setSelectedIndex(0); // 2010
        }
        
        // Теперь инициализируем ComboBox для дня (после того, как месяц и год установлены)
        updateDaysInMonth();
        jComboBoxDay.setBorder(javax.swing.BorderFactory.createTitledBorder("Tag"));
        
        // Устанавливаем текущий день по умолчанию
        int currentDay = cal.get(Calendar.DAY_OF_MONTH);
        if (jComboBoxDay.getItemCount() > 0) {
            // Убеждаемся, что выбранный день не превышает количество дней в месяце
            int maxDays = jComboBoxDay.getItemCount();
            if (currentDay <= maxDays) {
                jComboBoxDay.setSelectedIndex(currentDay - 1);
            } else {
                jComboBoxDay.setSelectedIndex(maxDays - 1);
            }
        }
        
        // Добавляем обработчики событий для обновления дней при изменении месяца или года
        jComboBoxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDaysInMonth();
                transferDateToTextArea5();
            }
        });
        
        jComboBoxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDaysInMonth();
                transferDateToTextArea5();
            }
        });
        
        jComboBoxDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferDateToTextArea5();
            }
        });
    }
    
    /**
     * Обновляет количество дней в ComboBox в зависимости от выбранного месяца и года
     */
    private void updateDaysInMonth() {
        // Проверяем, что ComboBox инициализированы
        if (jComboBoxMonth.getSelectedIndex() < 0 || jComboBoxYear.getSelectedItem() == null) {
            return; // Если еще не инициализированы, выходим
        }
        
        int selectedMonth = jComboBoxMonth.getSelectedIndex() + 1; // 1-12
        String yearString = (String) jComboBoxYear.getSelectedItem();
        if (yearString == null || yearString.trim().isEmpty()) {
            return; // Если год не выбран, выходим
        }
        
        int selectedYear;
        try {
            selectedYear = Integer.parseInt(yearString);
        } catch (NumberFormatException e) {
            System.err.println("Fehler beim Parsen des Jahres: " + yearString);
            return;
        }
        
        // Определяем количество дней в месяце
        int daysInMonth;
        if (selectedMonth == 2) { // Февраль
            // Проверяем високосный год
            boolean isLeapYear = (selectedYear % 4 == 0 && selectedYear % 100 != 0) || (selectedYear % 400 == 0);
            daysInMonth = isLeapYear ? 29 : 28;
        } else if (selectedMonth == 4 || selectedMonth == 6 || selectedMonth == 9 || selectedMonth == 11) {
            // Апрель, Июнь, Сентябрь, Ноябрь - 30 дней
            daysInMonth = 30;
        } else {
            // Остальные месяцы - 31 день
            daysInMonth = 31;
        }
        
        // Создаем массив дней
        String[] days = new String[daysInMonth];
        for (int i = 0; i < daysInMonth; i++) {
            days[i] = String.valueOf(i + 1);
        }
        
        // Сохраняем текущий выбранный день
        int currentSelectedDay = jComboBoxDay.getSelectedIndex() + 1;
        if (currentSelectedDay > daysInMonth) {
            currentSelectedDay = daysInMonth;
        }
        
        // Обновляем модель ComboBox
        jComboBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(days));
        
        // Восстанавливаем выбранный день (если он валиден)
        if (currentSelectedDay > 0 && currentSelectedDay <= daysInMonth) {
            jComboBoxDay.setSelectedIndex(currentSelectedDay - 1);
        } else {
            jComboBoxDay.setSelectedIndex(daysInMonth - 1);
        }
    }
    
    /**
     * Метод для переноса выбранной даты из ComboBox в jTextArea5
     */
    private void transferDateToTextArea5() {
        try {
            // Проверяем, что все ComboBox инициализированы и имеют выбранные значения
            if (jComboBoxDay.getSelectedItem() == null || 
                jComboBoxMonth.getSelectedIndex() < 0 || 
                jComboBoxYear.getSelectedItem() == null) {
                return; // Если что-то не выбрано, выходим
            }
            
            // Получаем выбранные значения из ComboBox
            String day = (String) jComboBoxDay.getSelectedItem();
            int monthIndex = jComboBoxMonth.getSelectedIndex() + 1; // 1-12
            String year = (String) jComboBoxYear.getSelectedItem();
            
            if (day == null || year == null) {
                return; // Если значения null, выходим
            }
            
            // Форматируем дату в формат dd.MM.yy (как используется в проекте)
            // Берем последние 2 цифры года
            String yearShort = year.substring(year.length() - 2);
            
            // Форматируем день с ведущим нулем, если нужно
            String dayFormatted = (day.length() == 1) ? "0" + day : day;
            
            // Форматируем месяц с ведущим нулем
            String monthFormatted = (monthIndex < 10) ? "0" + monthIndex : String.valueOf(monthIndex);
            
            // Формируем дату в формате dd.MM.yy
            String formattedDate = dayFormatted + "." + monthFormatted + "." + yearShort;
            
            // Устанавливаем дату в jTextArea5
            jTextArea5.setText(formattedDate);
            
        } catch (Exception e) {
            System.err.println("Fehler beim Übertragen der Datum: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NeuAnforderung01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NeuAnforderung01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NeuAnforderung01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NeuAnforderung01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NeuAnforderung01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> jComboBoxDay;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxYear;
    // End of variables declaration//GEN-END:variables
}
